### ISSUE TITLE
Add datadog provider in https://github.com/GoogleCloudPlatform/terraformer?

### ISSUE THREAD

**Issue by sergeylanzman** [kterada0509/datadog-terraformer#24]
https://github.com/GoogleCloudPlatform/terraformer

Terraformer new cli tool for export all configuration to tf and tfstate files.
It's very generic and work with many providers. Used provides binary for get all schema.

Maybe you want add datadog provider instead write/maintain other project?

**Comment by kterada0509** [comment]
@sergeylanzman 
Thanks for notification.
I try to add datadog provider to [GoogleCloudPlatform/terraformer](https://github.com/GoogleCloudPlatform/terraformer)

**Comment by kterada0509** [comment]
@sergeylanzman 
Would you mind  resolved this issue?

**Comment by sergeylanzman** [comment]
yes Thank you!
